---

- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  become: yes
  vars_files: [ 'roles/desktop/vars/personal.yml' ]

  roles:
    - andrewrothstein.terraform
    - andrewrothstein.kubernetes-helm
    - andrewrothstein.vagrant 
    - andrewrothstein.docker-machine
    - geerlingguy.ansible-role-packer
    - geerlingguy.docker
    - desktop
    - renderqwerty.ansible_galaxy_hadolint
    - viasite-ansible.zsh
    - renderqwerty.ansible_role_ruby
