---

- name: config max user watches for inotify
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present

- name: config user
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"

- name: gitconfig
  template:
    src: .gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"

- name: config kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: ssh_config
  copy:
    src: ssh/
    dest: /home/{{ username }}/.ssh/
    owner: "{{ username }}"
    group: "{{ username }}"

- name: config .ssh folder permissions
  file:
    state: directory
    path: ~/.ssh
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: config ssh keys permissions
  file:
    path: "{{ item }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  with_fileglob:
    - "/home/{{ username }}/.ssh/*.pub"

- name: setup dotfiles & shell
  block:
    - name: dotfiles
      git:
        repo: https://github.com/RenderQwerty/dotfiles.git
        dest: "/home/{{ username }}/.dotfiles"

    - name: autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: syntax highlight
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

    - name: stow links
      shell: stow *
      args:
        chdir: "/home/{{ username }}/.dotfiles"

  become_user: "{{ username }}"