---

- name: config max user watches for inotify
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present

- name: config kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: config user parameters
  user:
    name: "{{ username }}"
    append: yes
    groups:
        - vboxusers
        - vboxsf
        - docker
        - input

- name: enable fstrim
  systemd:
    name: fstrim.timer
    enabled: yes

- name: mask services
  systemd:
    name: "{{ item }}"
    masked: yes
  loop: "{{ disabled_units }}"
