---

- name: config max user watches for inotify
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present

- name: config kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: config user parameters
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
    append: yes
    groups:
        - vboxusers
        - vboxsf
        - docker
        - input

- name: enable fstrim
  systemd:
    name: fstrim.timer
    enabled: yes

- name: mask services
  systemd:
    name: "{{ item }}"
    masked: yes
  loop: "{{ disabled_units }}"


- name: setup dotfiles & shell
  block:
    - name: dotfiles
      git:
        repo: https://github.com/RenderQwerty/dotfiles.git
        dest: "/home/{{ username }}/.dotfiles"

    - name: autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: syntax highlight
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

    - name: stow links
      shell: stow *
      args:
        chdir: "/home/{{ username }}/.dotfiles"

  become_user: "{{ username }}"
