---

- name: config max user watches for inotify
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- name: config user
  user:
    name: "{{ item.username }}"
    shell: "/bin/zsh"
  loop: "{{ users }}"

- name: gitconfig
  template:
    src: .gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"

- name: config kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: ssh_config
  copy:
    src: ssh/
    dest: /home/{{ username }}/.ssh/
    owner: "{{ username }}"
    group: "{{ username }}"

- name: config .ssh folder permissions
  file:
    state: directory
    path: ~/.ssh
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: config ssh keys permissions
  file:
    path: "{{ item }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  with_fileglob:
    - "/home/{{ username }}/.ssh/*.pub"

- name: populate zsh config
  lineinfile:
    path: "/home/{{ username }}/.zshrc"
    create: yes
    line: "source <(kubectl completion zsh)"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: populate update script
  copy:
    src: update.sh
    dest: "/home/{{ username }}/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
