---

- name: config max user watches for inotify
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present

- name: gitconfig
  template:
    src: .gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"

- name: config kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf

- name: ssh_config
  copy:
    src: ssh/
    dest: /home/{{ username }}/.ssh/
    owner: "{{ username }}"
    group: "{{ username }}"

- name: config .ssh folder permissions
  file:
    state: directory
    path: ~/.ssh
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: config ssh keys permissions
  file:
    path: "{{ item }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  with_fileglob:
    - "/home/{{ username }}/.ssh/*.pub"

- name: config group membership
  user:
    name: "{{ username }}"
    append: yes
    groups:
        - vboxusers
        - vboxsf
        - docker
        - input

- name: enable fstrim
  systemd:
    name: fstrim.timer
    enabled: yes

- name: mask services
  systemd:
    name: "{{ item }}"
    masked: yes
  loop: "{{ disabled_units }}"
