---

- name: add chrome repo
  yum_repository:
    name: chrome
    description: google chrome repo
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64

- name: add rpmfusion repo
  dnf:
    name: "{{ repo_rpm_list }}"
    state: present
  
- name: add slack repo
  yum_repository:
    name: slack
    description: slack repo
    baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64

- name: add vscode repo
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode

- name: add k8s repo
  yum_repository:
    name: Kubernetes
    description: k8s
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

- name: add google cloud sdk
  yum_repository:
    name: gcloudsdk
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    description: Google Cloud SDK
    gpgkey: "{{ item }}"
  loop:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
