---

- name: install software
  dnf:
    name: "{{ item }}"
  loop:
    - "{{ deps_list }}"
    - "{{ install_list }}"
    - "{{ rpm_from_url }}"

- name: python modules
  pip:
    name: "{{ item.name }}"
    extra_args: --user
  loop: "{{ pip_install_packages }}"
  become_user: "{{ username }}"


#- name: install bin from web
#  get_url:
#    url: "{{ item }}"
#    dest: /usr/local/bin/
#    mode: 0755
#  loop: "{{ bin_from_url }}"

- name: install tflint
  unarchive:
    src: "{{ tflint }}"
    remote_src: yes
    dest: /usr/local/sbin
    mode: 0755

- name: remove default packages
  dnf:
    name: "{{ item }}"
    state: absent
  loop: "{{ remove_list }}"

- name: setup libinput for touchpad support
  git:
    repo: https://github.com/bulletmark/libinput-gestures.git
    dest: "/home/{{ username }}/git-projects/libinput-gestures"
