---

- name: add keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
    state: present
  loop: "{{ apt_key_list }}"


- name: add keys from url
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ gpg_key_list }}"

- name: add classic repositories
  apt_repository:
    repo: "{{ item }}"
    codename: bionic
  loop: "{{ repo_list }}"

- name: add ppa repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    codename: bionic
  loop: "{{ repo_list_ppa }}"
  notify: Update Cache
