---

- name: install software
  apt:
    name: "{{ item }}"
  loop:
    - "{{ deps_list }}"
    - "{{ install_list }}"


- name: install soft from url's
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ deb_from_url }}"


- name: python modules
  pip:
    name: "{{ item.name }}"
  loop: "{{ pip_install_packages }}"

#- name: install bin from web
#  get_url:
#    url: "{{ item }}"
#    dest: /usr/local/bin/
#    mode: 0755
#  loop: "{{ bin_from_url }}"

- name: install tflint
  unarchive:
    src: "{{ tflint }}"
    remote_src: yes
    dest: /usr/local/sbin
    mode: 0755

- name: remove default packages
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  loop: "{{ remove_list }}"
