---
- name: install some system dependecies
  apt:
    name: "{{ deps_list }}"
    state: present

- name: install software from repository
  tags: soft
  apt:
    name: "{{ install_list }}"
    state: latest

- name: install soft from url's
  tags: soft
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ deb_from_url }}"

# stub for ansible 2.8
#- name: install snap packages
#  snap:
#    name: "{{ item }}"
#    classic: yes
#  loop: "{{ snap_list }}"

- name: install ruby gems
  gem:
    name: "{{ item }}"
    state: latest
  loop: "{{ gem_list }}"

#- name: install bin from web
#  get_url:
#    url: "{{ item }}"
#    dest: /usr/local/bin/
#    mode: 0755
#  loop: "{{ bin_from_url }}"

- name: install tflint
  unarchive:
    src: "{{ tflint }}"
    remote_src: yes
    dest: /usr/local/sbin
    mode: 0755

- name: remove default packages
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  loop: "{{ remove_list }}"
