- name: gitconfig
  template:
    src: .gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"
    owner: "{{ username }}"

- name: ssh_config
  block:
    - copy:
        src: ssh/
        dest: /home/{{ username }}/.ssh/
        mode: 0700

    - file:
        path: "{{ item }}"
        mode: 0600
      with_fileglob:
        - "/home/{{ username }}/.ssh/*_rsa"

    - shell: ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      args:
        chdir: "/home/{{ username }}/.ssh/"
  become_user: "{{ username }}"
