---

- name: config max user watches for inotify
  tags: sysctl
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- name: config shell
  tags: shell
  user:
    name: "{{ username }}"
    shell: "/bin/zsh"
