---

- name: config max user watches for inotify
  tags: sysctl
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- name: config user
  tags: user
  user:
    name: "{{ username }}"
    shell: "/bin/zsh"

- name: config .ssh folder permissions
  file:
    state: directory
    path: ~/.ssh
    mode: 0700

- name: config ssh keys permissions
  file:
    path: "{{ item }}"
    mode: 0644
  with_fileglob:
    - "/home/{{ username }}/.ssh/*.pub"

