---

- name: config max user watches for inotify
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present

- name: config user
  user:
    name: "{{ item.username }}"
    shell: "/bin/zsh"
  loop: "{{ users }}"

- name: gitconfig
  template:
    src: .gitconfig.j2
    dest: "/home/{{ username }}/.gitconfig"

- name: ssh_config
  copy:
    src: ssh/
    dest: /home/{{ username }}/.ssh/

- name: config .ssh folder permissions
  file:
    state: directory
    path: ~/.ssh
    mode: 0700

- name: config ssh keys permissions
  file:
    path: "{{ item }}"
    mode: 0644
  with_fileglob:
    - "/home/{{ username }}/.ssh/*.pub"

- name: populate zsh config
  lineinfile:
    path: "/home/{{ username }}/.zshrc"
    line: "source <(kubectl completion zsh)"
