---
snap_list:
  - telegram-desktop
  - slack
  - skype
  - remmina
  - google-play-music-desktop-player

gem_list:
  - travis

install_from_url:
  - https://zoom.us/client/latest/zoom_amd64.deb

install_list:
  - chromium-browser
  - qbittorrent
  - keepassx
  - calibre
  - vim
  - virtualbox
  - virtualbox-ext-pack
  - virtualbox-guest-additions-iso
  - virtualbox-qt
  - virtualbox-dkms
  - zsh
  - zsh-common
  - snapd
  - ulauncher
  - sierra-gtk-theme
  - openssh-server
  - code
  - shellcheck
  - google-cloud-sdk
  - jq
  - fonts-powerline
  - exfat-fuse
  - exfat-utils
  - asciinema
  - openvpn
  - thunderbird
  - gnome-tweak-tool
  - gnome-shell-extension-appindicator
  - chrome-gnome-shell

deps_list:
  - cmake
  - build-essential
  - dkms
  - libgcrypt11-dev
  - libyajl-dev
  - libboost-all-dev
  - libcurl4-openssl-dev
  - libexpat1-dev
  - libcppunit-dev
  - binutils-dev
  - pkg-config
  - zlib1g-dev
  - gdebi-core
  - gtk2-engines-pixbuf
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - curl
  - gnome-themes-standard
  - gtk2-engines-murrine
  - dconf-editor
  - network-manager-l2tp
  - network-manager-l2tp-gnome
  - inotify-tools
  - debhelper
  - firewalld
  - ruby
  - ruby-dev

repo_list:
  - deb http://ppa.launchpad.net/dyatlov-igor/sierra-theme/ubuntu bionic main
  - deb http://packages.cloud.google.com/apt cloud-sdk-bionic main
  - ppa:agornostal/ulauncher
  - ppa:zanchey/asciinema
  - ppa:ubuntu-mozilla-security/ppa

remove_list:
  - firefox
