---

- name: install software
  apt:
   name: "{{ item }}"
   state: present
  with_items:
   - chromium-browser
   - qbittorrent
   - keepassx
   - calibre
   - vim
   - virtualbox
   - virtualbox-ext-pack
   - virtualbox-guest-additions-iso
   - virtualbox-qt
   - virtualbox-dkms
#   - skypeforlinux
   - zsh
   - zsh-common
   - vlc
   - snapd
#   - slack-desktop
   - neofetch
   - conky-all
   - vagrant
   - git
   - ulauncher

# using command module because ansible doesnt have snap module yet
- name: install snap packages
  command: snap install telegram-desktop --classic