---
- include_tasks: tasks/repo.yml
- include_tasks: tasks/install.yml

- name: remove default packages
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  loop: "{{ remove_list }}"

