- name: add keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BC012ECBBC24D881
    state: present

- name: add ulauncher ppa
  apt_repository: repo='ppa:agornostal/ulauncher' state=present

- name: Add repositories
  copy:
    src: "{{ role_path }}/files/repositories/"
    dest: /etc/apt/sources.list.d
    owner: root
    group: root

- name: update apt cache
  apt:
    update_cache: yes
