---

- name: install packages required for software compilation
  tags: deps
  apt:
   name: "{{ item }}"
   state: present
  with_items:
   - cmake
   - build-essential
   - dkms
   - libgcrypt11-dev
   - libyajl-dev
   - libboost-all-dev
   - libcurl4-openssl-dev
   - libexpat1-dev
   - libcppunit-dev
   - binutils-dev
   - pkg-config
   - zlib1g-dev
   - gdebi-core
   - gtk2-engines-pixbuf
   - apt-transport-https
   - ca-certificates
   - software-properties-common
   - curl
