---
- name: install some system dependecies
  tags: deps
  apt:
   name: "{{ item }}"
   state: present
  loop: "{{ deps_list }}"

- name: install software from repository
  tags: soft
  apt:
   name: "{{ item }}"
   state: present
  loop: "{{ install_list }}"


- name: install soft from url's
  tags: soft
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ install_from_url }}"

# using command module because ansible doesnt have snap module yet
- name: install snap packages
  command: "snap install {{ item }} --classic"
  loop: "{{ snap_list }}"
  tags: soft

- name: install python packages
  pip:
    name: "{{ item }}"
  loop: "{{ python_packages }}"
