---
- name: install some system dependecies
  tags: deps
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ deps_list }}"

- name: install software from repository
  tags: soft
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ install_list }}"

- name: install soft from url's
  tags: soft
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ deb_from_url }}"

- name: install snap packages
  snap:
    name: "{{ item }}"
    classic: yes
  loop: "{{ snap_list }}"

- name: install ruby gems
  gem:
    name: "{{ item }}"
    state: latest
  loop: "{{ gem_list }}"

- name: install bin from web
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  loop: "{{ bin_from_url }}"

- name: install tflint
  unarchive:
    src: "{{ tflint }}"
    remote_src: yes
    dest: /usr/local/sbin
    mode: 0755

- name: download gofish
  get_url:
    url: https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh
    dest: /tmp/gofish_installer.sh
    mode: 0755
- name: install gofish
  shell: /tmp/gofish_installer.sh
