---

- name: install software
  tags: soft_repo
  apt:
   name: "{{ item }}"
   state: present
  with_items:
   - chromium-browser
   - qbittorrent
   - keepassx
   - calibre
   - vim
   - virtualbox
   - virtualbox-ext-pack
   - virtualbox-guest-additions-iso
   - virtualbox-qt
   - virtualbox-dkms
   - zsh
   - zsh-common
   - vlc
   - snapd
   - neofetch
   - conky-all
   - vagrant
   - git
   - ulauncher
   - sierra-gtk-theme
   - openssh-server
   - code
   - shellcheck
   - google-cloud-sdk

# using command module because ansible doesnt have snap module yet
- name: install telegram
  command: snap install telegram-desktop --classic
  tags: soft_snap
  
- name: install slack
  command: snap install slack --classic
  tags: soft_snap

- name: install skype
  command: snap install skype --classic
  tags: soft_snap
