---
    
- name: install from url's
  tags: soft_url
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
   - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
   - https://zoom.us/client/latest/zoom_amd64.deb
