---

- name: install software from repository
  tags: soft
  apt:
   name: "{{ item }}"
   state: present
  loop:
   - chromium-browser
   - qbittorrent
   - keepassx
   - calibre
   - vim
   - virtualbox
   - virtualbox-ext-pack
   - virtualbox-guest-additions-iso
   - virtualbox-qt
   - virtualbox-dkms
   - zsh
   - zsh-common
   - vlc
   - snapd
   - neofetch
   - conky-all
   - vagrant
   - git
   - ulauncher
   - sierra-gtk-theme
   - openssh-server
   - code
   - shellcheck
   - google-cloud-sdk
   - jq
   - fonts-powerline
   - plank
   - asciinema

- name: install soft from url's
  tags: soft
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
   - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
   - https://zoom.us/client/latest/zoom_amd64.deb

   
# using command module because ansible doesnt have snap module yet
- name: install telegram
  command: snap install telegram-desktop --classic
  tags: soft_snap
  
- name: install slack
  command: snap install slack --classic
  tags: soft_snap

- name: install skype
  command: snap install skype --classic
  tags: soft_snap
