---

- name: install python packages
  pip:
    name: "{{ item }}"
  loop:
    - pipenv
    - virtualenv
    - docker-py
    - docker-compose
    - flake8
    - apache-libcloud
    - paramiko
    - PyYAML
    - jinja2
    - cryptography
    - httplib2
