---

- name: remove default packages
  apt:
    name: "{{ item }}"
    state: absent
    autoremove: yes
  loop: "{{ remove_list }}"

- name: remove snap packages
  shell: snap remove gnome-system-monitor && snap remove gnome-calculator
